### ISSUE TITLE
Improve browser compatibility 

### ISSUE THREAD

**Issue by stubailo** [stubailo/microhn#3]
For example, by removing the use of fetch!

**Comment by developit** [comment]
It's already relying on ES2015, any browser that supposed things like template literals and arrow functions would also support fetch.

**Comment by stubailo** [comment]
I don't think so - as far as I know, Safari supports everything I used except fetch.

**Comment by developit** [comment]
Yup, you're right. I actually just got bitten by this in a prototype!

**Comment by stubailo** [comment]
Added babel transpilation to get safari support. close enough!
